### ISSUE TITLE
testcase ui setup

### ISSUE THREAD

**Issue by tobiichi3227** [tobiichi3227/NTOJ-Judge#1]
- testcase download
- single testcases add/delete
- multiple testcases add/delete/update
- task group add/delete
- task group score update
- check type update
- score type update (only for contest)
- log all above action
@blameazu Is there anything missing?

**Comment by blameazu** [comment]
testcases names update(?

**Comment by tobiichi3227** [comment]
Ok.
You can just add anything you think needed and then send  a notification to
me.
